name: 1 - Public Build Pipeline
on:
  push:
    branches: [ main ]
    
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read
  actions: write # Necessário para upload de artefatos

jobs:
  build-package:
    runs-on: m4v3r1ck
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build Wheel
        run: |
          python -m pip install --upgrade build
          cd not_exploitable
          python -m build --wheel --outdir ../dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # Nome único para evitar conflitos, mas o ID do run garantirá a segurança
          name: package-pr-${{ github.event.pull_request.number }}
          path: dist/*.whl
          retention-days: 1
